--
-- PostgreSQL database dump
--

-- Dumped from database version 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO velocenetdb;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: velocenetdb
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO velocenetdb;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO velocenetdb;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: velocenetdb
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO velocenetdb;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO velocenetdb;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO velocenetdb;

--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "Avatar" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO velocenetdb;

--
-- Name: Cars; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."Cars" (
    "Id" integer NOT NULL,
    "Make" text,
    "Model" text,
    "Year" integer,
    "Vin" text,
    "Mileage" integer,
    "Price" numeric,
    "Features" text,
    "Condition" text,
    "ImagePath" text,
    "OwnerId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Cars" OWNER TO velocenetdb;

--
-- Name: Cars_Id_seq; Type: SEQUENCE; Schema: public; Owner: velocenetdb
--

ALTER TABLE public."Cars" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cars_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Owners; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."Owners" (
    "Id" integer NOT NULL,
    "Name" text,
    "ContactInfo" text,
    "Address" text
);


ALTER TABLE public."Owners" OWNER TO velocenetdb;

--
-- Name: Owners_Id_seq; Type: SEQUENCE; Schema: public; Owner: velocenetdb
--

ALTER TABLE public."Owners" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Owners_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sales; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."Sales" (
    "Id" integer NOT NULL,
    "CarId" integer NOT NULL,
    "OwnerId" integer NOT NULL,
    "SalePrice" numeric NOT NULL,
    "SaleDate" timestamp with time zone NOT NULL
);


ALTER TABLE public."Sales" OWNER TO velocenetdb;

--
-- Name: Sales_Id_seq; Type: SEQUENCE; Schema: public; Owner: velocenetdb
--

ALTER TABLE public."Sales" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sales_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: velocenetdb
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO velocenetdb;

--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
\.


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
\.


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."AspNetUsers" ("Id", "Avatar", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
ca01e10e-0d16-47ed-b22c-e0095f0fcaa1	\N	admin	ADMIN	test@example.com	TEST@EXAMPLE.COM	f	AQAAAAIAAYagAAAAEBBJKtPFmcu6RRrE5xiTT5GtzWv6oW8G5EX1RrFjdRZU56RNarrTZNNdIPwGSLx7yw==	BUDNF4CUFFDZQS6LH3GAJ3M6USATLFSK	df050167-4459-4fa7-958c-330235f17286	\N	f	f	\N	t	0
\.


--
-- Data for Name: Cars; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."Cars" ("Id", "Make", "Model", "Year", "Vin", "Mileage", "Price", "Features", "Condition", "ImagePath", "OwnerId", "CreatedAt", "UpdatedAt") FROM stdin;
2	Toyota	Camry	2020	1HGCM82633A123456	15000	23999.99	Bluetooth, Backup Camera, Remote Start	Used	\N	\N	2024-10-16 13:55:01.424921-04	2024-10-16 13:55:01.424922-04
3	New	Car	1999	5325235235235235	20	100000	Very mid.	New	\N	\N	2024-10-16 15:44:21.348997-04	2024-10-16 15:44:21.349042-04
6	Great	Wheels	1988	35135135135135	3515	500000	Slick	Classic	/uploads/0d75f205-bf85-4209-b3d6-684bbac7e4d1.jpg	\N	2024-10-16 16:00:52.547577-04	2024-10-16 16:00:52.5476-04
4	Bigger	Truck	1992	5135315135135	100000	500000	Pretty small, actually...	Classic	/uploads/d90f3327-6522-4370-abb9-daa6b4f2c35e.jpg	\N	2024-10-16 15:48:03.622967-04	2024-10-16 16:34:46.449143-04
5	Fish	Tank	1977	1235135135SDSFDSFASDFA	5	200000	Bubbles included.	New	/uploads/e3d74b86-36b3-43b9-a661-a985bdc46c4f.jpg	\N	2024-10-16 15:50:43.461394-04	2024-10-16 16:36:37.863107-04
\.


--
-- Data for Name: Owners; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."Owners" ("Id", "Name", "ContactInfo", "Address") FROM stdin;
\.


--
-- Data for Name: Sales; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."Sales" ("Id", "CarId", "OwnerId", "SalePrice", "SaleDate") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: velocenetdb
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20241016161351_Initial	8.0.10
\.


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: velocenetdb
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: velocenetdb
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: Cars_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: velocenetdb
--

SELECT pg_catalog.setval('public."Cars_Id_seq"', 6, true);


--
-- Name: Owners_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: velocenetdb
--

SELECT pg_catalog.setval('public."Owners_Id_seq"', 1, false);


--
-- Name: Sales_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: velocenetdb
--

SELECT pg_catalog.setval('public."Sales_Id_seq"', 1, false);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Cars PK_Cars; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."Cars"
    ADD CONSTRAINT "PK_Cars" PRIMARY KEY ("Id");


--
-- Name: Owners PK_Owners; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."Owners"
    ADD CONSTRAINT "PK_Owners" PRIMARY KEY ("Id");


--
-- Name: Sales PK_Sales; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "PK_Sales" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_Cars_OwnerId; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE INDEX "IX_Cars_OwnerId" ON public."Cars" USING btree ("OwnerId");


--
-- Name: IX_Sales_CarId; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE INDEX "IX_Sales_CarId" ON public."Sales" USING btree ("CarId");


--
-- Name: IX_Sales_OwnerId; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE INDEX "IX_Sales_OwnerId" ON public."Sales" USING btree ("OwnerId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: velocenetdb
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: Cars FK_Cars_Owners_OwnerId; Type: FK CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."Cars"
    ADD CONSTRAINT "FK_Cars_Owners_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES public."Owners"("Id") ON DELETE SET NULL;


--
-- Name: Sales FK_Sales_Cars_CarId; Type: FK CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "FK_Sales_Cars_CarId" FOREIGN KEY ("CarId") REFERENCES public."Cars"("Id") ON DELETE CASCADE;


--
-- Name: Sales FK_Sales_Owners_OwnerId; Type: FK CONSTRAINT; Schema: public; Owner: velocenetdb
--

ALTER TABLE ONLY public."Sales"
    ADD CONSTRAINT "FK_Sales_Owners_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES public."Owners"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

