version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=YourConnectionStringHere
      - Jwt__Issuer=YourIssuerHere
      - Jwt__Audience=YourAudienceHere
      - Jwt__Key=YourJwtKeyHere
    networks:
      - veloce_network

networks:
  veloce_network:
